### ISSUE TITLE
Evaluate 3rd party Elasticsearch hosting providers

### ISSUE THREAD

**Issue by trietlu** [1T/aws-centralized-logging#6]
Due to our complex logging use case, we would need to dedicate engineering efforts to build and maintain a robust Elasticsearch solution.  We are looking at 3rd party vendors to free up our engineers to focus on 1Ticket domain work

The desired outcome from this issue to to have had discussion with and received price quotes from selected vendors.  After that, we'll make a decision on moving forward with a vendor or homegrown solution

**Comment by trietlu** [comment]
Joe and I spoke to a company called Albatross last week, regarding a managed logging solution. Attached is a quote we received from them base on our discussions.

~/r



---------- Forwarded message ----------
From: Karim Roumani <karim.roumani@tekreach.com>
Date: Fri, Jul 6, 2018 at 6:24 PM
Subject: Re: Graylog
To: John Reggy <reggy@1ticket.com>, joe@1ticket.com


John & Joe,

Here's the attached proposal. This should do what you need. I suggest you do month to month to make sure the solution works as you expect then you can lock in a lower rate for the long term once things are working. 

Without Yearly Agreement: $2,975.00  (start here).
With Yearly Agreement:  $2,275.00

100 Mbps should be sufficient
4 TB of hot space. A little room for growth. 7 Day hot data.
Excellent IO performance SSDs.
30 Day cold storage retention.
We will support you on making sure your solution works just as you expect as part of SLA on hardware, infrastructure and basic configs and operations in Graylog. 

Let me know if how this looks or if you want to add anything.
ᐧ

On Thu, Jul 5, 2018 at 2:05 PM Karim Roumani <karim.roumani@tekreach.com> wrote:
John,

Just left you a VM. You can reach me at 714-916-5677
ᐧ

On Tue, May 29, 2018 at 5:05 PM Karim Roumani <karim.roumani@tekreach.com> wrote:
I'll have a quote soon.
ᐧ

On Tue, May 29, 2018 at 11:52 AM, John Reggy <reggy@1ticket.com> wrote:

current self hosted graylog environment config
==
Number of servers: 5
Number of CPUs:   2 per server
Amount of RAM:  4 GB per server (current usage is 75% or higher)
Retention policy:  60 days
Disk space (Elasticsearch data):  346 GB per server


On Thu, May 17, 2018 at 2:54 PM, Karim Roumani <karim.roumani@tekreach.com> wrote:
Reggy,

Good talking to you today. Please let me know 

- How much disk space your system uses today
- How long is your retention policy
- CPU / RAM requirements that you currently have.
- Number of servers

-- 
Thank you,

Karim Roumani
Director of Technology Solutions



TekReach Solutions / Albatross Cloud
714-916-5677
Karim.Roumani@tekreach.com
Albatross.cloud - One Stop Cloud Solutions
Portalfronthosting.com - Complete SharePoint Solutions

**Comment by trietlu** [comment]
Requirements for vendors:

1Ticket is looking for a fully managed Elasticsearch hosting solution on AWS.  We are logging upwards of 500GB of data per day, with each log entry ranging from 2K - 10K in size. The data is logged evenly throughout the day.  However, we may have bursts that are 25% above average when our customers perform certain actions.  About one third of the data logged is associated with one index, another third with another index, and about a dozen other log sources are grouped to use another index.  Each index currently has about 2 dozen mapped fields, though that number can be reduced.  Our Support team queries the logs to investigate customer inquiries at a rate of about a query a minute.  The queries may span log entries across days.  We need the log data to be on hot/fast storage for 7 days to support customer inquiries.  For data between 7 days and 30 days, we can tolerate a slower query performance.  Our retention period is 30 days, after which we need the data to be archived.  We need for the archived data to be able of being restored within 1 day.

**Comment by trietlu** [comment]
@r10 is reaching out to other vendors

**Comment by r10** [comment]
**Logz.io unique differentiators & questions we help with:**

How do we architect ELK, parse the logs properly, and ensure it's stable + reliable?
How do we drive reliability via proactive analytics? (alerts + AI)
How do we support at scale via access controls + data segregation?
Who will provide support & training? 
Here's a link to our case study on how we've helped Dyn reduce the time to identify issues by 50% via proactive analytics: https://logz.io/case-studies/risk-reduction-resource-optimization-logz-io/

**Additional Resources**
Video from Dyn discussing experience from using Logz.io: https://www.youtube.com/watch?v=uPX7VHk7bqs
Case study on how Rent-A-Center uses Logz.io cognitive insights to find root access issue in logs: https://logz.io/news/rent-a-center-logz-io/
Public website G2 Crowd Logz.io reviews from customers such as Bazaarvoice & Turner Broadcasting: https://www.g2crowd.com/products/logz-io/reviews
Security + Compliance Whitepaper: http://logz.io/wp-content/uploads/2017/01/Security-and-Compliance-Whitepaper.pdf

**Comment by trietlu** [comment]
[https://app.zenhub.com/files/130751159/c0bdfd11-3141-4a58-8d88-19682cc96c83/download](https://app.zenhub.com/files/130751159/c0bdfd11-3141-4a58-8d88-19682cc96c83/download)
